name: 2019_scheibler_overiva
dependencies:
  - python=3.7
  - numpy
  - scipy>=0.18.0
  - matplotlib
  - pip:
    - gitpython
    - pyroomacoustics=0.1.23
    - sounddevice
    - samplerate
    - mir_eval
